# =====================================================================================================
# PLAYBOOK DE ROLLBACK TOTAL: Desfaz as configurações do Orion Workstation
# =====================================================================================================
# Descrição:
#   Este playbook executa um rollback completo do Orion Workstation, removendo
#   todos os pacotes listados nas roles, independentemente de estarem instalados ou não.
#
#   Resumo:
#   - O parâmetro `ignore_errors: true` é utilizado nas tarefas de desinstalação para garantir
#       que o playbook continue executando mesmo que algum pacote não esteja instalado.
#       Isso evita que o processo de rollback seja interrompido por falhas não críticas.
#
#   Funcionamento:
#     - Tenta desinstalar todas as ações realizadas nas roles, mesmo que alguns deles nunca tenham
#       sido instalados (por exemplo, se apenas o AWS CLI foi instalado, ainda assim
#       tentará remover Azure CLI e Google Cloud CLI).
#     - Limpa dependências não utilizadas após a remoção dos pacotes.
#
#   Atenção:
#     - Recomenda-se fortemente realizar backup dos dados importantes antes de executar.
# =====================================================================================================

- name: ORION WORKSTATION - ROLLBACK TOTAL
  hosts: localhost
  connection: local

  vars_files:
    - "roles/packages_optional/defaults/main.yml"
    - "roles/docker_container/defaults/main.yml"
    - "roles/kubernetes_orchestration/defaults/main.yml"
    - "roles/web_servers/defaults/main.yml"

  tasks:
    - name: "SEGURANCA | Muda o shell padrão para BASH"
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/bash

    - name: "PACKAGES | Reverte a instalação dos pacotes opcionais"
      become: true
      ansible.builtin.apt:
        name: "{{ optional_packages }}"
        state: absent
        purge: true

    - name: "OhMyZSH | Reverte a instalação e configuração do Oh My Zsh"
      block:
        - name: Remove arquivos e diretórios do Zsh
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "/home/{{ ansible_user_id }}/.oh-my-zsh"
            - "/home/{{ ansible_user_id }}/.zshrc"
            - "/home/{{ ansible_user_id }}/.zsh_history"
            - "/home/{{ ansible_user_id }}/.p10k.zsh"

        - name: Desinstala o pacote zsh
          become: true
          ansible.builtin.apt:
            name: zsh
            state: absent
            purge: true

    - name: "ROLLBACK | Reverte a instalação e configuração do Docker"
      block:
        - name: "DOCKER | Coleta os fatos sobre os serviços do sistema"
          ansible.builtin.service_facts:

        - name: "DOCKER | Para e desabilita os serviços do Docker (se existirem)"
          become: true
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop:
            - "{{ docker_service }}"
          when: item in ansible_facts.services

        - name: "DOCKER | Remove o grupo 'docker'"
          become: true
          ansible.builtin.group:
            name: docker
            state: absent

        - name: "DOCKER | Remove os pacotes do Docker e seus componentes"
          become: true
          ansible.builtin.apt:
            name: "{{ packages_docker }}"
            state: absent
            purge: true
            autoremove: yes

        - name: "DOCKER | Remove o arquivo de repositório do Docker"
          become: true
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/docker.list
            state: absent

        - name: "DOCKER | Remove a chave GPG do Docker"
          become: true
          ansible.builtin.file:
            path: /etc/apt/keyrings/docker.gpg
            state: absent

        - name: "DOCKER | Remove o diretório de dados do Docker (ATENÇÃO: AÇÃO DESTRUTIVA)"
          become: true
          ansible.builtin.file:
            path: /var/lib/docker
            state: absent

    - name: "ROLLBACK | Reverte a instalação completa do ecossistema Kubernetes"
      block:
        - name: "KUBERNETES | Remove arquivos de configuração e cache do Helm"
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "/home/{{ ansible_user_id }}/.config/helm"
            - "/home/{{ ansible_user_id }}/.cache/helm"

        - name: "KUBERNETES | Remove os pacotes do Kubernetes (usando dpkg)"
          become: true
          ansible.builtin.command:
            cmd: "dpkg --purge {{ item }}"
          loop: "{{ kubernetes_packages }}"
          register: dpkg_purge_result
          changed_when: "'purging' in dpkg_purge_result.stdout"
          ignore_errors: true

        - name: "KUBERNETES | Remove o arquivo de repositório APT do Kubernetes"
          become: true
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/kubernetes.list
            state: absent

        - name: "KUBERNETES | Remove a chave GPG do repositório Kubernetes"
          become: true
          ansible.builtin.file:
            path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
            state: absent

        - name: "KUBERNETES | Remove os binários (minikube, helm, k9s)"
          become: true
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop: "{{ kubernetes_bin_path }}"

    - name: "ROLLBACK | Reverte a instalação dos servidores web"
      block:
      - name: "WEB_SERVERS | Atualiza o cache de pacotes antes da remoção"
        become: true
        ansible.builtin.apt:
          update_cache: true

      - name: "WEB_SERVERS | Remove os servidores web instalados"
        become: true
        ansible.builtin.apt:
          name: "{{ web_servers_install }}"
          state: absent
          purge: true

    - name: "ROLLBACK | Limpeza completa do APT"
      block:
      - name: "ROLLBACK | Remove pacotes não utilizados"
        become: true
        ansible.builtin.apt:
          autoremove: true

      - name: "ROLLBACK | Limpa os diretórios de cache do APT"
        become: true
        ansible.builtin.apt:
          autoclean: true
