---
# Esta tarefa Ansible instala os bancos de dados SQL listados na variável
# 'db_sql_install' e garante que seus serviços não iniciem automaticamente.
# Para adicionar ou remover bancos de dados, modifique a variável
# 'db_sql_install' no arquivo default/main.yml.

- name: "DATABASES | Instala os pacotes de bancos de dados SQL selecionados"
  become: true
  ansible.builtin.apt:
    name: "{{ database_sql_packages }}"
    state: present
    update_cache: yes

- name: "DATABASES | Garante que os serviços dos bancos de dados estejam parados e desabilitados"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ database_sql_services }}"
  