---
# Este arquivo define a lista padrão de pacotes do ZSH a serem instalados.
#
# zsh_packages:
#   Estes pacotes são essenciais para uma instalação moderna do ZSH, incluindo
#   o shell, o utilitário de download (curl) e o controle de versões (git).
zsh_packages:
  - zsh
  - curl
  - git

# Nome do tema que sera utilizado no ZSH.
# Pode ser alterado para outro tema do Powerlevel10k ou outro tema de sua preferencia.
# Exemplo: "agnoster", "robbyrussell", etc.
zsh_theme_name: "powerlevel10k/powerlevel10k"

...