---
# Versões do Kubernetes
kubernetes_version: "1.31"

# Versões das ferramentas
helm_version: "3.15.2"
k9s_version: "0.32.5"

# Pacotes Kubernetes a serem instalados
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

# Local binário dos pacotes Kubernetes
kubernetes_bin_path:
  - /usr/local/bin/minikube
  - /usr/local/bin/helm
  - /usr/local/bin/k9s
