---
# =============================================================================
# PLAYBOOK: Configuração Automatizada de Ambiente WSL2 Ubuntu
# =============================================================================
# Descrição:
#   Este playbook realiza a configuração modular de um ambiente de
#   desenvolvimento no WSL2 Ubuntu usando roles.
#
# Autor: Ihan Messias Nascimento dos Santos
# Email: codeverso.academy@gmail.com
# Linkedin: https://www.linkedin.com/in/ihanmessias/
# =============================================================================

- name: ORION WORKSTATION
  hosts: localhost
  connection: local

  roles:
    - role: update_system
      when: setup.update_system | bool
    - role: packages_optional
      when: setup.packages_optional | bool
    - role: oh_my_zsh
      when: setup.oh_my_zsh | bool
    - role: docker_container
      when: setup.docker_container | bool
    - role: kubernetes_orchestration
      when: setup.kubernetes_orchestration | bool
    - role: iac
      when: setup.iac | bool
    - role: cloud_cli
      when: setup.cloud_cli | bool
